# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aml/mmoconstructor/3d/metagam3d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aml/mmoconstructor/3d/metagam3d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aml/mmoconstructor/3d/metagam3d/CMakeFiles /home/aml/mmoconstructor/3d/metagam3d/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aml/mmoconstructor/3d/metagam3d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named convertModel

# Build rule for target.
convertModel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convertModel
.PHONY : convertModel

# fast build rule for target.
convertModel/fast:
	$(MAKE) -f CMakeFiles/convertModel.dir/build.make CMakeFiles/convertModel.dir/build
.PHONY : convertModel/fast

#=============================================================================
# Target rules for targets named metagam3d

# Build rule for target.
metagam3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 metagam3d
.PHONY : metagam3d

# fast build rule for target.
metagam3d/fast:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/build
.PHONY : metagam3d/fast

#=============================================================================
# Target rules for targets named testDynamicValue

# Build rule for target.
testDynamicValue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testDynamicValue
.PHONY : testDynamicValue

# fast build rule for target.
testDynamicValue/fast:
	$(MAKE) -f CMakeFiles/testDynamicValue.dir/build.make CMakeFiles/testDynamicValue.dir/build
.PHONY : testDynamicValue/fast

#=============================================================================
# Target rules for targets named testScriptAssembler

# Build rule for target.
testScriptAssembler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testScriptAssembler
.PHONY : testScriptAssembler

# fast build rule for target.
testScriptAssembler/fast:
	$(MAKE) -f CMakeFiles/testScriptAssembler.dir/build.make CMakeFiles/testScriptAssembler.dir/build
.PHONY : testScriptAssembler/fast

#=============================================================================
# Target rules for targets named testScriptExpression

# Build rule for target.
testScriptExpression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testScriptExpression
.PHONY : testScriptExpression

# fast build rule for target.
testScriptExpression/fast:
	$(MAKE) -f CMakeFiles/testScriptExpression.dir/build.make CMakeFiles/testScriptExpression.dir/build
.PHONY : testScriptExpression/fast

#=============================================================================
# Target rules for targets named testVariant

# Build rule for target.
testVariant: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testVariant
.PHONY : testVariant

# fast build rule for target.
testVariant/fast:
	$(MAKE) -f CMakeFiles/testVariant.dir/build.make CMakeFiles/testVariant.dir/build
.PHONY : testVariant/fast

src/CameraManipulator.o: src/CameraManipulator.cc.o
.PHONY : src/CameraManipulator.o

# target to build an object file
src/CameraManipulator.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/CameraManipulator.cc.o
.PHONY : src/CameraManipulator.cc.o

src/CameraManipulator.i: src/CameraManipulator.cc.i
.PHONY : src/CameraManipulator.i

# target to preprocess a source file
src/CameraManipulator.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/CameraManipulator.cc.i
.PHONY : src/CameraManipulator.cc.i

src/CameraManipulator.s: src/CameraManipulator.cc.s
.PHONY : src/CameraManipulator.s

# target to generate assembly for a file
src/CameraManipulator.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/CameraManipulator.cc.s
.PHONY : src/CameraManipulator.cc.s

src/ConsoleObject.o: src/ConsoleObject.cc.o
.PHONY : src/ConsoleObject.o

# target to build an object file
src/ConsoleObject.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ConsoleObject.cc.o
.PHONY : src/ConsoleObject.cc.o

src/ConsoleObject.i: src/ConsoleObject.cc.i
.PHONY : src/ConsoleObject.i

# target to preprocess a source file
src/ConsoleObject.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ConsoleObject.cc.i
.PHONY : src/ConsoleObject.cc.i

src/ConsoleObject.s: src/ConsoleObject.cc.s
.PHONY : src/ConsoleObject.s

# target to generate assembly for a file
src/ConsoleObject.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ConsoleObject.cc.s
.PHONY : src/ConsoleObject.cc.s

src/DynamicValue.o: src/DynamicValue.cc.o
.PHONY : src/DynamicValue.o

# target to build an object file
src/DynamicValue.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/DynamicValue.cc.o
.PHONY : src/DynamicValue.cc.o

src/DynamicValue.i: src/DynamicValue.cc.i
.PHONY : src/DynamicValue.i

# target to preprocess a source file
src/DynamicValue.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/DynamicValue.cc.i
.PHONY : src/DynamicValue.cc.i

src/DynamicValue.s: src/DynamicValue.cc.s
.PHONY : src/DynamicValue.s

# target to generate assembly for a file
src/DynamicValue.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/DynamicValue.cc.s
.PHONY : src/DynamicValue.cc.s

src/Engine.o: src/Engine.cc.o
.PHONY : src/Engine.o

# target to build an object file
src/Engine.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/Engine.cc.o
.PHONY : src/Engine.cc.o

src/Engine.i: src/Engine.cc.i
.PHONY : src/Engine.i

# target to preprocess a source file
src/Engine.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/Engine.cc.i
.PHONY : src/Engine.cc.i

src/Engine.s: src/Engine.cc.s
.PHONY : src/Engine.s

# target to generate assembly for a file
src/Engine.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/Engine.cc.s
.PHONY : src/Engine.cc.s

src/OSGConsole.o: src/OSGConsole.cc.o
.PHONY : src/OSGConsole.o

# target to build an object file
src/OSGConsole.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/OSGConsole.cc.o
.PHONY : src/OSGConsole.cc.o

src/OSGConsole.i: src/OSGConsole.cc.i
.PHONY : src/OSGConsole.i

# target to preprocess a source file
src/OSGConsole.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/OSGConsole.cc.i
.PHONY : src/OSGConsole.cc.i

src/OSGConsole.s: src/OSGConsole.cc.s
.PHONY : src/OSGConsole.s

# target to generate assembly for a file
src/OSGConsole.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/OSGConsole.cc.s
.PHONY : src/OSGConsole.cc.s

src/OSGMailbox.o: src/OSGMailbox.cc.o
.PHONY : src/OSGMailbox.o

# target to build an object file
src/OSGMailbox.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/OSGMailbox.cc.o
.PHONY : src/OSGMailbox.cc.o

src/OSGMailbox.i: src/OSGMailbox.cc.i
.PHONY : src/OSGMailbox.i

# target to preprocess a source file
src/OSGMailbox.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/OSGMailbox.cc.i
.PHONY : src/OSGMailbox.cc.i

src/OSGMailbox.s: src/OSGMailbox.cc.s
.PHONY : src/OSGMailbox.s

# target to generate assembly for a file
src/OSGMailbox.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/OSGMailbox.cc.s
.PHONY : src/OSGMailbox.cc.s

src/OSGMessage.o: src/OSGMessage.cc.o
.PHONY : src/OSGMessage.o

# target to build an object file
src/OSGMessage.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/OSGMessage.cc.o
.PHONY : src/OSGMessage.cc.o

src/OSGMessage.i: src/OSGMessage.cc.i
.PHONY : src/OSGMessage.i

# target to preprocess a source file
src/OSGMessage.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/OSGMessage.cc.i
.PHONY : src/OSGMessage.cc.i

src/OSGMessage.s: src/OSGMessage.cc.s
.PHONY : src/OSGMessage.s

# target to generate assembly for a file
src/OSGMessage.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/OSGMessage.cc.s
.PHONY : src/OSGMessage.cc.s

src/Object.o: src/Object.cc.o
.PHONY : src/Object.o

# target to build an object file
src/Object.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/Object.cc.o
.PHONY : src/Object.cc.o

src/Object.i: src/Object.cc.i
.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/Object.cc.i
.PHONY : src/Object.cc.i

src/Object.s: src/Object.cc.s
.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/Object.cc.s
.PHONY : src/Object.cc.s

src/ObjectDestroyMessage.o: src/ObjectDestroyMessage.cc.o
.PHONY : src/ObjectDestroyMessage.o

# target to build an object file
src/ObjectDestroyMessage.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectDestroyMessage.cc.o
.PHONY : src/ObjectDestroyMessage.cc.o

src/ObjectDestroyMessage.i: src/ObjectDestroyMessage.cc.i
.PHONY : src/ObjectDestroyMessage.i

# target to preprocess a source file
src/ObjectDestroyMessage.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectDestroyMessage.cc.i
.PHONY : src/ObjectDestroyMessage.cc.i

src/ObjectDestroyMessage.s: src/ObjectDestroyMessage.cc.s
.PHONY : src/ObjectDestroyMessage.s

# target to generate assembly for a file
src/ObjectDestroyMessage.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectDestroyMessage.cc.s
.PHONY : src/ObjectDestroyMessage.cc.s

src/ObjectManager.o: src/ObjectManager.cc.o
.PHONY : src/ObjectManager.o

# target to build an object file
src/ObjectManager.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectManager.cc.o
.PHONY : src/ObjectManager.cc.o

src/ObjectManager.i: src/ObjectManager.cc.i
.PHONY : src/ObjectManager.i

# target to preprocess a source file
src/ObjectManager.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectManager.cc.i
.PHONY : src/ObjectManager.cc.i

src/ObjectManager.s: src/ObjectManager.cc.s
.PHONY : src/ObjectManager.s

# target to generate assembly for a file
src/ObjectManager.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectManager.cc.s
.PHONY : src/ObjectManager.cc.s

src/ObjectMaterialHandler.o: src/ObjectMaterialHandler.cc.o
.PHONY : src/ObjectMaterialHandler.o

# target to build an object file
src/ObjectMaterialHandler.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectMaterialHandler.cc.o
.PHONY : src/ObjectMaterialHandler.cc.o

src/ObjectMaterialHandler.i: src/ObjectMaterialHandler.cc.i
.PHONY : src/ObjectMaterialHandler.i

# target to preprocess a source file
src/ObjectMaterialHandler.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectMaterialHandler.cc.i
.PHONY : src/ObjectMaterialHandler.cc.i

src/ObjectMaterialHandler.s: src/ObjectMaterialHandler.cc.s
.PHONY : src/ObjectMaterialHandler.s

# target to generate assembly for a file
src/ObjectMaterialHandler.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectMaterialHandler.cc.s
.PHONY : src/ObjectMaterialHandler.cc.s

src/ObjectMotionHandler.o: src/ObjectMotionHandler.cc.o
.PHONY : src/ObjectMotionHandler.o

# target to build an object file
src/ObjectMotionHandler.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectMotionHandler.cc.o
.PHONY : src/ObjectMotionHandler.cc.o

src/ObjectMotionHandler.i: src/ObjectMotionHandler.cc.i
.PHONY : src/ObjectMotionHandler.i

# target to preprocess a source file
src/ObjectMotionHandler.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectMotionHandler.cc.i
.PHONY : src/ObjectMotionHandler.cc.i

src/ObjectMotionHandler.s: src/ObjectMotionHandler.cc.s
.PHONY : src/ObjectMotionHandler.s

# target to generate assembly for a file
src/ObjectMotionHandler.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectMotionHandler.cc.s
.PHONY : src/ObjectMotionHandler.cc.s

src/ObjectParamHandler.o: src/ObjectParamHandler.cc.o
.PHONY : src/ObjectParamHandler.o

# target to build an object file
src/ObjectParamHandler.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectParamHandler.cc.o
.PHONY : src/ObjectParamHandler.cc.o

src/ObjectParamHandler.i: src/ObjectParamHandler.cc.i
.PHONY : src/ObjectParamHandler.i

# target to preprocess a source file
src/ObjectParamHandler.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectParamHandler.cc.i
.PHONY : src/ObjectParamHandler.cc.i

src/ObjectParamHandler.s: src/ObjectParamHandler.cc.s
.PHONY : src/ObjectParamHandler.s

# target to generate assembly for a file
src/ObjectParamHandler.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectParamHandler.cc.s
.PHONY : src/ObjectParamHandler.cc.s

src/ObjectParamSetMessage.o: src/ObjectParamSetMessage.cc.o
.PHONY : src/ObjectParamSetMessage.o

# target to build an object file
src/ObjectParamSetMessage.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectParamSetMessage.cc.o
.PHONY : src/ObjectParamSetMessage.cc.o

src/ObjectParamSetMessage.i: src/ObjectParamSetMessage.cc.i
.PHONY : src/ObjectParamSetMessage.i

# target to preprocess a source file
src/ObjectParamSetMessage.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectParamSetMessage.cc.i
.PHONY : src/ObjectParamSetMessage.cc.i

src/ObjectParamSetMessage.s: src/ObjectParamSetMessage.cc.s
.PHONY : src/ObjectParamSetMessage.s

# target to generate assembly for a file
src/ObjectParamSetMessage.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectParamSetMessage.cc.s
.PHONY : src/ObjectParamSetMessage.cc.s

src/ObjectTextHandler.o: src/ObjectTextHandler.cc.o
.PHONY : src/ObjectTextHandler.o

# target to build an object file
src/ObjectTextHandler.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectTextHandler.cc.o
.PHONY : src/ObjectTextHandler.cc.o

src/ObjectTextHandler.i: src/ObjectTextHandler.cc.i
.PHONY : src/ObjectTextHandler.i

# target to preprocess a source file
src/ObjectTextHandler.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectTextHandler.cc.i
.PHONY : src/ObjectTextHandler.cc.i

src/ObjectTextHandler.s: src/ObjectTextHandler.cc.s
.PHONY : src/ObjectTextHandler.s

# target to generate assembly for a file
src/ObjectTextHandler.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectTextHandler.cc.s
.PHONY : src/ObjectTextHandler.cc.s

src/ObjectVectorHandler.o: src/ObjectVectorHandler.cc.o
.PHONY : src/ObjectVectorHandler.o

# target to build an object file
src/ObjectVectorHandler.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectVectorHandler.cc.o
.PHONY : src/ObjectVectorHandler.cc.o

src/ObjectVectorHandler.i: src/ObjectVectorHandler.cc.i
.PHONY : src/ObjectVectorHandler.i

# target to preprocess a source file
src/ObjectVectorHandler.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectVectorHandler.cc.i
.PHONY : src/ObjectVectorHandler.cc.i

src/ObjectVectorHandler.s: src/ObjectVectorHandler.cc.s
.PHONY : src/ObjectVectorHandler.s

# target to generate assembly for a file
src/ObjectVectorHandler.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ObjectVectorHandler.cc.s
.PHONY : src/ObjectVectorHandler.cc.s

src/RunScriptCommand.o: src/RunScriptCommand.cc.o
.PHONY : src/RunScriptCommand.o

# target to build an object file
src/RunScriptCommand.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/RunScriptCommand.cc.o
.PHONY : src/RunScriptCommand.cc.o

src/RunScriptCommand.i: src/RunScriptCommand.cc.i
.PHONY : src/RunScriptCommand.i

# target to preprocess a source file
src/RunScriptCommand.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/RunScriptCommand.cc.i
.PHONY : src/RunScriptCommand.cc.i

src/RunScriptCommand.s: src/RunScriptCommand.cc.s
.PHONY : src/RunScriptCommand.s

# target to generate assembly for a file
src/RunScriptCommand.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/RunScriptCommand.cc.s
.PHONY : src/RunScriptCommand.cc.s

src/ScriptAssembler.o: src/ScriptAssembler.cc.o
.PHONY : src/ScriptAssembler.o

# target to build an object file
src/ScriptAssembler.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ScriptAssembler.cc.o
.PHONY : src/ScriptAssembler.cc.o

src/ScriptAssembler.i: src/ScriptAssembler.cc.i
.PHONY : src/ScriptAssembler.i

# target to preprocess a source file
src/ScriptAssembler.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ScriptAssembler.cc.i
.PHONY : src/ScriptAssembler.cc.i

src/ScriptAssembler.s: src/ScriptAssembler.cc.s
.PHONY : src/ScriptAssembler.s

# target to generate assembly for a file
src/ScriptAssembler.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ScriptAssembler.cc.s
.PHONY : src/ScriptAssembler.cc.s

src/ScriptEnvironment.o: src/ScriptEnvironment.cc.o
.PHONY : src/ScriptEnvironment.o

# target to build an object file
src/ScriptEnvironment.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ScriptEnvironment.cc.o
.PHONY : src/ScriptEnvironment.cc.o

src/ScriptEnvironment.i: src/ScriptEnvironment.cc.i
.PHONY : src/ScriptEnvironment.i

# target to preprocess a source file
src/ScriptEnvironment.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ScriptEnvironment.cc.i
.PHONY : src/ScriptEnvironment.cc.i

src/ScriptEnvironment.s: src/ScriptEnvironment.cc.s
.PHONY : src/ScriptEnvironment.s

# target to generate assembly for a file
src/ScriptEnvironment.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ScriptEnvironment.cc.s
.PHONY : src/ScriptEnvironment.cc.s

src/ScriptExpression.o: src/ScriptExpression.cc.o
.PHONY : src/ScriptExpression.o

# target to build an object file
src/ScriptExpression.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ScriptExpression.cc.o
.PHONY : src/ScriptExpression.cc.o

src/ScriptExpression.i: src/ScriptExpression.cc.i
.PHONY : src/ScriptExpression.i

# target to preprocess a source file
src/ScriptExpression.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ScriptExpression.cc.i
.PHONY : src/ScriptExpression.cc.i

src/ScriptExpression.s: src/ScriptExpression.cc.s
.PHONY : src/ScriptExpression.s

# target to generate assembly for a file
src/ScriptExpression.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/ScriptExpression.cc.s
.PHONY : src/ScriptExpression.cc.s

src/StacklessChannel.o: src/StacklessChannel.cc.o
.PHONY : src/StacklessChannel.o

# target to build an object file
src/StacklessChannel.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessChannel.cc.o
.PHONY : src/StacklessChannel.cc.o

src/StacklessChannel.i: src/StacklessChannel.cc.i
.PHONY : src/StacklessChannel.i

# target to preprocess a source file
src/StacklessChannel.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessChannel.cc.i
.PHONY : src/StacklessChannel.cc.i

src/StacklessChannel.s: src/StacklessChannel.cc.s
.PHONY : src/StacklessChannel.s

# target to generate assembly for a file
src/StacklessChannel.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessChannel.cc.s
.PHONY : src/StacklessChannel.cc.s

src/StacklessChannelValue.o: src/StacklessChannelValue.cc.o
.PHONY : src/StacklessChannelValue.o

# target to build an object file
src/StacklessChannelValue.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessChannelValue.cc.o
.PHONY : src/StacklessChannelValue.cc.o

src/StacklessChannelValue.i: src/StacklessChannelValue.cc.i
.PHONY : src/StacklessChannelValue.i

# target to preprocess a source file
src/StacklessChannelValue.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessChannelValue.cc.i
.PHONY : src/StacklessChannelValue.cc.i

src/StacklessChannelValue.s: src/StacklessChannelValue.cc.s
.PHONY : src/StacklessChannelValue.s

# target to generate assembly for a file
src/StacklessChannelValue.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessChannelValue.cc.s
.PHONY : src/StacklessChannelValue.cc.s

src/StacklessConsole.o: src/StacklessConsole.cc.o
.PHONY : src/StacklessConsole.o

# target to build an object file
src/StacklessConsole.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessConsole.cc.o
.PHONY : src/StacklessConsole.cc.o

src/StacklessConsole.i: src/StacklessConsole.cc.i
.PHONY : src/StacklessConsole.i

# target to preprocess a source file
src/StacklessConsole.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessConsole.cc.i
.PHONY : src/StacklessConsole.cc.i

src/StacklessConsole.s: src/StacklessConsole.cc.s
.PHONY : src/StacklessConsole.s

# target to generate assembly for a file
src/StacklessConsole.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessConsole.cc.s
.PHONY : src/StacklessConsole.cc.s

src/StacklessLines.o: src/StacklessLines.cc.o
.PHONY : src/StacklessLines.o

# target to build an object file
src/StacklessLines.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessLines.cc.o
.PHONY : src/StacklessLines.cc.o

src/StacklessLines.i: src/StacklessLines.cc.i
.PHONY : src/StacklessLines.i

# target to preprocess a source file
src/StacklessLines.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessLines.cc.i
.PHONY : src/StacklessLines.cc.i

src/StacklessLines.s: src/StacklessLines.cc.s
.PHONY : src/StacklessLines.s

# target to generate assembly for a file
src/StacklessLines.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessLines.cc.s
.PHONY : src/StacklessLines.cc.s

src/StacklessMailbox.o: src/StacklessMailbox.cc.o
.PHONY : src/StacklessMailbox.o

# target to build an object file
src/StacklessMailbox.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMailbox.cc.o
.PHONY : src/StacklessMailbox.cc.o

src/StacklessMailbox.i: src/StacklessMailbox.cc.i
.PHONY : src/StacklessMailbox.i

# target to preprocess a source file
src/StacklessMailbox.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMailbox.cc.i
.PHONY : src/StacklessMailbox.cc.i

src/StacklessMailbox.s: src/StacklessMailbox.cc.s
.PHONY : src/StacklessMailbox.s

# target to generate assembly for a file
src/StacklessMailbox.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMailbox.cc.s
.PHONY : src/StacklessMailbox.cc.s

src/StacklessMaterialParam.o: src/StacklessMaterialParam.cc.o
.PHONY : src/StacklessMaterialParam.o

# target to build an object file
src/StacklessMaterialParam.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMaterialParam.cc.o
.PHONY : src/StacklessMaterialParam.cc.o

src/StacklessMaterialParam.i: src/StacklessMaterialParam.cc.i
.PHONY : src/StacklessMaterialParam.i

# target to preprocess a source file
src/StacklessMaterialParam.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMaterialParam.cc.i
.PHONY : src/StacklessMaterialParam.cc.i

src/StacklessMaterialParam.s: src/StacklessMaterialParam.cc.s
.PHONY : src/StacklessMaterialParam.s

# target to generate assembly for a file
src/StacklessMaterialParam.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMaterialParam.cc.s
.PHONY : src/StacklessMaterialParam.cc.s

src/StacklessMath.o: src/StacklessMath.cc.o
.PHONY : src/StacklessMath.o

# target to build an object file
src/StacklessMath.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMath.cc.o
.PHONY : src/StacklessMath.cc.o

src/StacklessMath.i: src/StacklessMath.cc.i
.PHONY : src/StacklessMath.i

# target to preprocess a source file
src/StacklessMath.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMath.cc.i
.PHONY : src/StacklessMath.cc.i

src/StacklessMath.s: src/StacklessMath.cc.s
.PHONY : src/StacklessMath.s

# target to generate assembly for a file
src/StacklessMath.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMath.cc.s
.PHONY : src/StacklessMath.cc.s

src/StacklessMessage.o: src/StacklessMessage.cc.o
.PHONY : src/StacklessMessage.o

# target to build an object file
src/StacklessMessage.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMessage.cc.o
.PHONY : src/StacklessMessage.cc.o

src/StacklessMessage.i: src/StacklessMessage.cc.i
.PHONY : src/StacklessMessage.i

# target to preprocess a source file
src/StacklessMessage.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMessage.cc.i
.PHONY : src/StacklessMessage.cc.i

src/StacklessMessage.s: src/StacklessMessage.cc.s
.PHONY : src/StacklessMessage.s

# target to generate assembly for a file
src/StacklessMessage.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessMessage.cc.s
.PHONY : src/StacklessMessage.cc.s

src/StacklessObject.o: src/StacklessObject.cc.o
.PHONY : src/StacklessObject.o

# target to build an object file
src/StacklessObject.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessObject.cc.o
.PHONY : src/StacklessObject.cc.o

src/StacklessObject.i: src/StacklessObject.cc.i
.PHONY : src/StacklessObject.i

# target to preprocess a source file
src/StacklessObject.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessObject.cc.i
.PHONY : src/StacklessObject.cc.i

src/StacklessObject.s: src/StacklessObject.cc.s
.PHONY : src/StacklessObject.s

# target to generate assembly for a file
src/StacklessObject.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessObject.cc.s
.PHONY : src/StacklessObject.cc.s

src/StacklessObjectLoader.o: src/StacklessObjectLoader.cc.o
.PHONY : src/StacklessObjectLoader.o

# target to build an object file
src/StacklessObjectLoader.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessObjectLoader.cc.o
.PHONY : src/StacklessObjectLoader.cc.o

src/StacklessObjectLoader.i: src/StacklessObjectLoader.cc.i
.PHONY : src/StacklessObjectLoader.i

# target to preprocess a source file
src/StacklessObjectLoader.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessObjectLoader.cc.i
.PHONY : src/StacklessObjectLoader.cc.i

src/StacklessObjectLoader.s: src/StacklessObjectLoader.cc.s
.PHONY : src/StacklessObjectLoader.s

# target to generate assembly for a file
src/StacklessObjectLoader.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessObjectLoader.cc.s
.PHONY : src/StacklessObjectLoader.cc.s

src/StacklessObjectParam.o: src/StacklessObjectParam.cc.o
.PHONY : src/StacklessObjectParam.o

# target to build an object file
src/StacklessObjectParam.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessObjectParam.cc.o
.PHONY : src/StacklessObjectParam.cc.o

src/StacklessObjectParam.i: src/StacklessObjectParam.cc.i
.PHONY : src/StacklessObjectParam.i

# target to preprocess a source file
src/StacklessObjectParam.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessObjectParam.cc.i
.PHONY : src/StacklessObjectParam.cc.i

src/StacklessObjectParam.s: src/StacklessObjectParam.cc.s
.PHONY : src/StacklessObjectParam.s

# target to generate assembly for a file
src/StacklessObjectParam.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessObjectParam.cc.s
.PHONY : src/StacklessObjectParam.cc.s

src/StacklessText.o: src/StacklessText.cc.o
.PHONY : src/StacklessText.o

# target to build an object file
src/StacklessText.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessText.cc.o
.PHONY : src/StacklessText.cc.o

src/StacklessText.i: src/StacklessText.cc.i
.PHONY : src/StacklessText.i

# target to preprocess a source file
src/StacklessText.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessText.cc.i
.PHONY : src/StacklessText.cc.i

src/StacklessText.s: src/StacklessText.cc.s
.PHONY : src/StacklessText.s

# target to generate assembly for a file
src/StacklessText.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessText.cc.s
.PHONY : src/StacklessText.cc.s

src/StacklessThread.o: src/StacklessThread.cc.o
.PHONY : src/StacklessThread.o

# target to build an object file
src/StacklessThread.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessThread.cc.o
.PHONY : src/StacklessThread.cc.o

src/StacklessThread.i: src/StacklessThread.cc.i
.PHONY : src/StacklessThread.i

# target to preprocess a source file
src/StacklessThread.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessThread.cc.i
.PHONY : src/StacklessThread.cc.i

src/StacklessThread.s: src/StacklessThread.cc.s
.PHONY : src/StacklessThread.s

# target to generate assembly for a file
src/StacklessThread.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/StacklessThread.cc.s
.PHONY : src/StacklessThread.cc.s

src/Variant.o: src/Variant.cc.o
.PHONY : src/Variant.o

# target to build an object file
src/Variant.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/Variant.cc.o
.PHONY : src/Variant.cc.o

src/Variant.i: src/Variant.cc.i
.PHONY : src/Variant.i

# target to preprocess a source file
src/Variant.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/Variant.cc.i
.PHONY : src/Variant.cc.i

src/Variant.s: src/Variant.cc.s
.PHONY : src/Variant.s

# target to generate assembly for a file
src/Variant.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/Variant.cc.s
.PHONY : src/Variant.cc.s

src/errors.o: src/errors.cc.o
.PHONY : src/errors.o

# target to build an object file
src/errors.cc.o:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/errors.cc.o
.PHONY : src/errors.cc.o

src/errors.i: src/errors.cc.i
.PHONY : src/errors.i

# target to preprocess a source file
src/errors.cc.i:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/errors.cc.i
.PHONY : src/errors.cc.i

src/errors.s: src/errors.cc.s
.PHONY : src/errors.s

# target to generate assembly for a file
src/errors.cc.s:
	$(MAKE) -f CMakeFiles/metagam3d.dir/build.make CMakeFiles/metagam3d.dir/src/errors.cc.s
.PHONY : src/errors.cc.s

test/DynamicValue.o: test/DynamicValue.cc.o
.PHONY : test/DynamicValue.o

# target to build an object file
test/DynamicValue.cc.o:
	$(MAKE) -f CMakeFiles/testDynamicValue.dir/build.make CMakeFiles/testDynamicValue.dir/test/DynamicValue.cc.o
.PHONY : test/DynamicValue.cc.o

test/DynamicValue.i: test/DynamicValue.cc.i
.PHONY : test/DynamicValue.i

# target to preprocess a source file
test/DynamicValue.cc.i:
	$(MAKE) -f CMakeFiles/testDynamicValue.dir/build.make CMakeFiles/testDynamicValue.dir/test/DynamicValue.cc.i
.PHONY : test/DynamicValue.cc.i

test/DynamicValue.s: test/DynamicValue.cc.s
.PHONY : test/DynamicValue.s

# target to generate assembly for a file
test/DynamicValue.cc.s:
	$(MAKE) -f CMakeFiles/testDynamicValue.dir/build.make CMakeFiles/testDynamicValue.dir/test/DynamicValue.cc.s
.PHONY : test/DynamicValue.cc.s

test/ScriptAssembler.o: test/ScriptAssembler.cc.o
.PHONY : test/ScriptAssembler.o

# target to build an object file
test/ScriptAssembler.cc.o:
	$(MAKE) -f CMakeFiles/testScriptAssembler.dir/build.make CMakeFiles/testScriptAssembler.dir/test/ScriptAssembler.cc.o
.PHONY : test/ScriptAssembler.cc.o

test/ScriptAssembler.i: test/ScriptAssembler.cc.i
.PHONY : test/ScriptAssembler.i

# target to preprocess a source file
test/ScriptAssembler.cc.i:
	$(MAKE) -f CMakeFiles/testScriptAssembler.dir/build.make CMakeFiles/testScriptAssembler.dir/test/ScriptAssembler.cc.i
.PHONY : test/ScriptAssembler.cc.i

test/ScriptAssembler.s: test/ScriptAssembler.cc.s
.PHONY : test/ScriptAssembler.s

# target to generate assembly for a file
test/ScriptAssembler.cc.s:
	$(MAKE) -f CMakeFiles/testScriptAssembler.dir/build.make CMakeFiles/testScriptAssembler.dir/test/ScriptAssembler.cc.s
.PHONY : test/ScriptAssembler.cc.s

test/ScriptExpression.o: test/ScriptExpression.cc.o
.PHONY : test/ScriptExpression.o

# target to build an object file
test/ScriptExpression.cc.o:
	$(MAKE) -f CMakeFiles/testScriptExpression.dir/build.make CMakeFiles/testScriptExpression.dir/test/ScriptExpression.cc.o
.PHONY : test/ScriptExpression.cc.o

test/ScriptExpression.i: test/ScriptExpression.cc.i
.PHONY : test/ScriptExpression.i

# target to preprocess a source file
test/ScriptExpression.cc.i:
	$(MAKE) -f CMakeFiles/testScriptExpression.dir/build.make CMakeFiles/testScriptExpression.dir/test/ScriptExpression.cc.i
.PHONY : test/ScriptExpression.cc.i

test/ScriptExpression.s: test/ScriptExpression.cc.s
.PHONY : test/ScriptExpression.s

# target to generate assembly for a file
test/ScriptExpression.cc.s:
	$(MAKE) -f CMakeFiles/testScriptExpression.dir/build.make CMakeFiles/testScriptExpression.dir/test/ScriptExpression.cc.s
.PHONY : test/ScriptExpression.cc.s

test/Variant.o: test/Variant.cc.o
.PHONY : test/Variant.o

# target to build an object file
test/Variant.cc.o:
	$(MAKE) -f CMakeFiles/testVariant.dir/build.make CMakeFiles/testVariant.dir/test/Variant.cc.o
.PHONY : test/Variant.cc.o

test/Variant.i: test/Variant.cc.i
.PHONY : test/Variant.i

# target to preprocess a source file
test/Variant.cc.i:
	$(MAKE) -f CMakeFiles/testVariant.dir/build.make CMakeFiles/testVariant.dir/test/Variant.cc.i
.PHONY : test/Variant.cc.i

test/Variant.s: test/Variant.cc.s
.PHONY : test/Variant.s

# target to generate assembly for a file
test/Variant.cc.s:
	$(MAKE) -f CMakeFiles/testVariant.dir/build.make CMakeFiles/testVariant.dir/test/Variant.cc.s
.PHONY : test/Variant.cc.s

tools/convertModel.o: tools/convertModel.cc.o
.PHONY : tools/convertModel.o

# target to build an object file
tools/convertModel.cc.o:
	$(MAKE) -f CMakeFiles/convertModel.dir/build.make CMakeFiles/convertModel.dir/tools/convertModel.cc.o
.PHONY : tools/convertModel.cc.o

tools/convertModel.i: tools/convertModel.cc.i
.PHONY : tools/convertModel.i

# target to preprocess a source file
tools/convertModel.cc.i:
	$(MAKE) -f CMakeFiles/convertModel.dir/build.make CMakeFiles/convertModel.dir/tools/convertModel.cc.i
.PHONY : tools/convertModel.cc.i

tools/convertModel.s: tools/convertModel.cc.s
.PHONY : tools/convertModel.s

# target to generate assembly for a file
tools/convertModel.cc.s:
	$(MAKE) -f CMakeFiles/convertModel.dir/build.make CMakeFiles/convertModel.dir/tools/convertModel.cc.s
.PHONY : tools/convertModel.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... convertModel"
	@echo "... edit_cache"
	@echo "... metagam3d"
	@echo "... rebuild_cache"
	@echo "... testDynamicValue"
	@echo "... testScriptAssembler"
	@echo "... testScriptExpression"
	@echo "... testVariant"
	@echo "... src/CameraManipulator.o"
	@echo "... src/CameraManipulator.i"
	@echo "... src/CameraManipulator.s"
	@echo "... src/ConsoleObject.o"
	@echo "... src/ConsoleObject.i"
	@echo "... src/ConsoleObject.s"
	@echo "... src/DynamicValue.o"
	@echo "... src/DynamicValue.i"
	@echo "... src/DynamicValue.s"
	@echo "... src/Engine.o"
	@echo "... src/Engine.i"
	@echo "... src/Engine.s"
	@echo "... src/OSGConsole.o"
	@echo "... src/OSGConsole.i"
	@echo "... src/OSGConsole.s"
	@echo "... src/OSGMailbox.o"
	@echo "... src/OSGMailbox.i"
	@echo "... src/OSGMailbox.s"
	@echo "... src/OSGMessage.o"
	@echo "... src/OSGMessage.i"
	@echo "... src/OSGMessage.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/ObjectDestroyMessage.o"
	@echo "... src/ObjectDestroyMessage.i"
	@echo "... src/ObjectDestroyMessage.s"
	@echo "... src/ObjectManager.o"
	@echo "... src/ObjectManager.i"
	@echo "... src/ObjectManager.s"
	@echo "... src/ObjectMaterialHandler.o"
	@echo "... src/ObjectMaterialHandler.i"
	@echo "... src/ObjectMaterialHandler.s"
	@echo "... src/ObjectMotionHandler.o"
	@echo "... src/ObjectMotionHandler.i"
	@echo "... src/ObjectMotionHandler.s"
	@echo "... src/ObjectParamHandler.o"
	@echo "... src/ObjectParamHandler.i"
	@echo "... src/ObjectParamHandler.s"
	@echo "... src/ObjectParamSetMessage.o"
	@echo "... src/ObjectParamSetMessage.i"
	@echo "... src/ObjectParamSetMessage.s"
	@echo "... src/ObjectTextHandler.o"
	@echo "... src/ObjectTextHandler.i"
	@echo "... src/ObjectTextHandler.s"
	@echo "... src/ObjectVectorHandler.o"
	@echo "... src/ObjectVectorHandler.i"
	@echo "... src/ObjectVectorHandler.s"
	@echo "... src/RunScriptCommand.o"
	@echo "... src/RunScriptCommand.i"
	@echo "... src/RunScriptCommand.s"
	@echo "... src/ScriptAssembler.o"
	@echo "... src/ScriptAssembler.i"
	@echo "... src/ScriptAssembler.s"
	@echo "... src/ScriptEnvironment.o"
	@echo "... src/ScriptEnvironment.i"
	@echo "... src/ScriptEnvironment.s"
	@echo "... src/ScriptExpression.o"
	@echo "... src/ScriptExpression.i"
	@echo "... src/ScriptExpression.s"
	@echo "... src/StacklessChannel.o"
	@echo "... src/StacklessChannel.i"
	@echo "... src/StacklessChannel.s"
	@echo "... src/StacklessChannelValue.o"
	@echo "... src/StacklessChannelValue.i"
	@echo "... src/StacklessChannelValue.s"
	@echo "... src/StacklessConsole.o"
	@echo "... src/StacklessConsole.i"
	@echo "... src/StacklessConsole.s"
	@echo "... src/StacklessLines.o"
	@echo "... src/StacklessLines.i"
	@echo "... src/StacklessLines.s"
	@echo "... src/StacklessMailbox.o"
	@echo "... src/StacklessMailbox.i"
	@echo "... src/StacklessMailbox.s"
	@echo "... src/StacklessMaterialParam.o"
	@echo "... src/StacklessMaterialParam.i"
	@echo "... src/StacklessMaterialParam.s"
	@echo "... src/StacklessMath.o"
	@echo "... src/StacklessMath.i"
	@echo "... src/StacklessMath.s"
	@echo "... src/StacklessMessage.o"
	@echo "... src/StacklessMessage.i"
	@echo "... src/StacklessMessage.s"
	@echo "... src/StacklessObject.o"
	@echo "... src/StacklessObject.i"
	@echo "... src/StacklessObject.s"
	@echo "... src/StacklessObjectLoader.o"
	@echo "... src/StacklessObjectLoader.i"
	@echo "... src/StacklessObjectLoader.s"
	@echo "... src/StacklessObjectParam.o"
	@echo "... src/StacklessObjectParam.i"
	@echo "... src/StacklessObjectParam.s"
	@echo "... src/StacklessText.o"
	@echo "... src/StacklessText.i"
	@echo "... src/StacklessText.s"
	@echo "... src/StacklessThread.o"
	@echo "... src/StacklessThread.i"
	@echo "... src/StacklessThread.s"
	@echo "... src/Variant.o"
	@echo "... src/Variant.i"
	@echo "... src/Variant.s"
	@echo "... src/errors.o"
	@echo "... src/errors.i"
	@echo "... src/errors.s"
	@echo "... test/DynamicValue.o"
	@echo "... test/DynamicValue.i"
	@echo "... test/DynamicValue.s"
	@echo "... test/ScriptAssembler.o"
	@echo "... test/ScriptAssembler.i"
	@echo "... test/ScriptAssembler.s"
	@echo "... test/ScriptExpression.o"
	@echo "... test/ScriptExpression.i"
	@echo "... test/ScriptExpression.s"
	@echo "... test/Variant.o"
	@echo "... test/Variant.i"
	@echo "... test/Variant.s"
	@echo "... tools/convertModel.o"
	@echo "... tools/convertModel.i"
	@echo "... tools/convertModel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

